name: poem_verse_app
description: A beautiful poetry application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  http: ^1.2.1
  flutter_cache_manager: ^3.3.2
  app_links: ^6.1.4
  flutter_widget_from_html: ^0.14.11
  photo_view: ^0.14.0
  flutter_image_compress: ^2.2.0
  image_cropper: ^6.0.0
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  video_player: ^2.8.6
  chewie: ^1.8.1
  uuid: ^4.4.0
  intl: ^0.20.2
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: FZZhaoGY
      fonts:
        - asset: assets/fonts/FZZhaoGYJW-R.ttf
